nav:
  - Home: 'index.md'
  - Notes:
    - 0. Overview: '00-overview.md'
    - 1. Program and Compiler: '01-compiler.md'
    - 2. Variable and Type: '02-type.md'
    - 3. Functions: '03-function.md'
    - 4. Encapsultion: '04-encapsulation.md'
    - 5. Information Hiding: '05-infohiding.md'
    - 6. Tell, Don't Ask: '06-tell-dont-ask.md'
    - 7. Class Fields: '07-static-field.md'
  - Guide:
    - Programming Environments: 'environments.md'

    #  - General: 
    #- About CS2030S: 'about.md'
    #- Learning Outcomes: 'outcomes.md'
    #- Schedule: 'schedule.md'
    #- Accounts: 'accounts.md'
    #- Policies: 'policies.md'
    #  - Notes: 
    #  - Readings: 'readings.md'
    #  - Software/Tools:
    #     - Programming Environments: 'environments.md'
    #   - UNIX: 'unix.md'
    #   - CLang: 'clang.md'
    #   - Vim: 'vim.md'
    #   - TMate: 'tmate.md'
    #   - Zoom: 'zoom.md'
    #  - Older Announcements: 'archive.md'
    #  - 17/18 Sem 2: '1718s2.md'
        
theme: 
  name: material
  shortcuts:
    previous: 72 #h
    next: 76 #l
    search: 191 #/

site_name: CS2030S Programming Methodology II
# repo_url: https://github.com/nus-cs1010/1819-s1
site_url: https://nus-cs2030s.github.io/2021-s2
copyright: Copyright by Department of Computer Science, National University of Singapore 2021
# remote_branch: gh-pages
use_directory_urls: false
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
     linenums: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
  - 'stylesheets/extra.css'
  - 'https://fonts.googleapis.com/css?family=Roboto:400,700'
  - 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap'
